version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - .:/var/www/symfony
    depends_on:
      - php
    restart: always

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: preguntados
    ports:
      - 127.1.5.20:5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  php:
    build: .docker/php-fpm
    volumes:
      - .:/var/www/symfony
    depends_on:
      - db
    restart: always

volumes:
  db_data:
